# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ata_piix" "ahci" "tifm_7xx1" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/crypted";
      fsType = "ext4";
    };

  boot.initrd.luks.devices.crypted.device = "/dev/sda2";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/97b21675-b594-43a4-ba64-cd99dbadfbd4";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/75efb1ac-afce-40b6-a166-2813ff676aac"; }
    ];

  nix.maxJobs = lib.mkDefault 2;
  networking.enableIntel3945ABGFirmware = true;
}
